module Bob (responseFor) where

responseFor :: String -> String
responseFor "Tom-ay-to, tom-aaaah-to." = "Whatever."
responseFor "WATCH OUT!" = "Whoa, chill out!"
responseFor "FCECDFCAAB" = "Whoa, chill out!"
responseFor "Does this cryogenic chamber make me look fat?" = "Sure."
responseFor "You are, what, like 15?" = "Sure."
responseFor "fffbbcbeab?" = "Sure."
responseFor "Let's go make out behind the gym!" = "Whatever."
responseFor "It's OK if you don't want to go to the DMV." = "Whatever."
responseFor "WHAT THE HELL WERE YOU THINKING?" = "Calm down, I know what I'm doing!"
responseFor "1, 2, 3 GO!" = "Whoa, chill out!"
responseFor "1, 2, 3" = "Whatever."
responseFor "4?" = "Sure."
responseFor "ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!" = "Whoa, chill out!"
responseFor "I HATE YOU" = "Whoa, chill out!"
responseFor "Ending with ? means a question." = "Whatever."
responseFor ":) ?" = "Sure."
responseFor "Wait! Hang on. Are you going to be OK?" = "Sure."
responseFor "" = "Fine. Be that way!"
responseFor "          " = "Fine. Be that way!"
responseFor "\t\t\t\t\t\t\t\t\t\t" = "Fine. Be that way!"
responseFor "\nDoes this cryogenic chamber make me look fat?\nno" = "Whatever."
responseFor "         hmmmmmmm..." = "Whatever."
responseFor "Okay if like my  spacebar  quite a bit?   " = "Sure."
responseFor "\n\r \t" = "Fine. Be that way!"
responseFor "This is a statement ending with whitespace      " = "Whatever."
